pipeline {
    agent {
        docker { 
            image "adrianobma/node-wd" 
            args "--network=skynet"
        }
    }
    stages {
        stage('Build') {
            steps {
                sh "npm install"
            } 
        }
        stage('Tests') {
            steps {
                sh "npm run test:ci"
                // junit testResults: "tests_output/**/*.xml"
            }
            post {
                always {
                    // junit testResults: "tests_output/**/*.xml"
                    junit testDataPublishers:[[$class: 'AttachmentPublisher']], testResults: "tests_output/**/*.xml"
                }
            }
        }
    }
}